spring:
  application:
    name: aggregator

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      client-id: aggregator-client
      enable-auto-commit: false
      topic: telemetry.sensors.v1
    producer:
      topic: telemetry.snapshots.v1