@namespace("ru.yandex.practicum.kafka.telemetry.event")
protocol HubEventProtocol {
    enum DeviceTypeAvro {
		MOTION_SENSOR,
		TEMPERATURE_SENSOR,
		LIGHT_SENSOR,
		CLIMATE_SENSOR,
		SWITCH_SENSOR
	}

	enum ConditionTypeAvro {
		MOTION,
		LUMINOSITY,
		SWITCH,
		TEMPERATURE,
		CO2LEVEL,
		HUMIDITY
	}

	enum ConditionOperationAvro {
		EQUALS,
		GREATER_THAN,
		LOWER_THAN
	}

	enum ActionTypeAvro {
		ACTIVATE,
		DEACTIVATE,
		INVERSE,
		SET_VALUE
	}

	enum HubEventTypeAvro {
		DEVICE_ADDED,
		DEVICE_REMOVED,
		SCENARIO_ADDED,
		SCENARIO_REMOVED
	}

	record ScenarioConditionAvro {
		string sensorId;
		ConditionTypeAvro type;
		ConditionOperationAvro operation;
		union { null, int, boolean } value = null;
	}

	record DeviceActionAvro {
		string sensorId;
		ActionTypeAvro type;
		int? value = null;
	}

	record DeviceAddedEventAvro {
		string id;
		DeviceTypeAvro deviceType;
	}

	record DeviceRemovedEventAvro {
		string id;
	}

	record ScenarioAddedEventAvro {
		string name;
		array<ScenarioConditionAvro> conditions;
		array<DeviceActionAvro> actions;
	}

	record ScenarioRemovedEventAvro {
		string name;
	}

	record HubEventAvro {
		string hubId;
		long timestamp;
		union {
			DeviceAddedEventAvro,
			DeviceRemovedEventAvro,
			ScenarioAddedEventAvro,
			ScenarioRemovedEventAvro
		} payload;
	}
}